(autoload 'color-theme-solarized                "color-theme-solarized" "" t)
(autoload 'color-theme-solarized-dark           "color-theme-solarized" "" t)
(autoload 'color-theme-solarized-light          "color-theme-solarized" "" t)
(autoload 'solarized-color-definitions          "solarized-definitions" "" nil)
(autoload 'create-solarized-theme               "solarized-definitions" "" nil 'macro)
(provide 'color-theme-solarized-epackage-autoloads)
